Addicted2:
  Saves: 47
  Party: '&fMai este nevoie de &c%voturi% voturi &fpana incepe party-ul!'
  PartyFinish: Ai primit toate premile!
  MesajCountdown: Eventul incepe in &e&l%time% &fsecunde!
  Countdown: 10
  Start: '&fMega Party-ul incepe incepe imediat &c(100/100 voturi stranse)!'
  Total: 50
  ActionBarVote: '&c%player% &fa votat serverul &4&l/vote &f- &fVoteParty &7%voturi%/50'

